# Generated by Django 4.1.7 on 2023-03-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updatedValue',
            new_name='updated',
        ),
    ]
