# Generated by Django 4.1.7 on 2023-03-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_options_rename_updatedvalue_room_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='updatedValue',
            new_name='updated',
        ),
    ]
